### ISSUE TITLE
live chat dnt comment (

### ISSUE THREAD

**Issue by Ondrik8** [sasi-kumar-repo/CommentYoutubeLiveChat#1]
driver.find_element("self.chat_input_field[0], self.chat_input_field[1]")

` Message: invalid argument: invalid locator`

**Comment by sasi-kumar-repo** [comment]
@Ondrik8 we shouldn't pass it as a string, self.chat_input_field[0] will have locator to be used and self.chat_input_field[1] will have locator string to be used. Actually you should modify the line with the below one to make it work

https://github.com/sasi-kumar-repo/CommentYoutubeLiveChat/blob/python-youtubelivechat-selenium/libs/youtube_base.py#L111
